//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace oooooo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tAnnouncement
    {
        [DisplayName("公告編號")]
        public int fAnnouncementId { get; set; }
        [Required(ErrorMessage = "標題不可空白")]
        [DisplayName("標題")]
        public string fAnnTitle { get; set; }
        [DisplayName("公告日期")]
        public string fAnnDate { get; set; }
        [DisplayName("管委會")]
        public string fUserId { get; set; }
        [DisplayName("公告內容")]
        public string fAnnContent { get; set; }
        [DisplayName("瀏覽量")]
        public Nullable<int> fClickRate { get; set; }
        [DisplayName("照片路徑")]
        public string fAnnFilePath { get; set; }
        [DisplayName("照片")]
        public HttpPostedFileBase fImage { get; set; }

        public virtual tMemberData tMemberData { get; set; }
    }
}
