//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace oooooo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEventRegister
    {
        public int fEventRegisterId { get; set; }
        public string fUserId { get; set; }
        public Nullable<int> fEventId { get; set; }
        public Nullable<int> fnumAttendPeople { get; set; }
        public string fAttendName { get; set; }
        public string ferBirthday { get; set; }
        public string ferIdentity { get; set; }
        public string ferGender { get; set; }
        public string ferEducation { get; set; }
        public string ferOccupation { get; set; }
        public string ferBloodType { get; set; }
        public string ferMarrige { get; set; }
    
        public virtual tEvent tEvent { get; set; }
        public virtual tMemberData tMemberData { get; set; }
    }
}
