//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace oooooo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tEvent()
        {
            this.tEventRegister = new HashSet<tEventRegister>();
        }
    
        public int fEventId { get; set; }
        public string fEventTitle { get; set; }
        public string fCategory { get; set; }
        public string fEventFromDay { get; set; }
        public string fEventEndDate { get; set; }
        public string fUserId { get; set; }
        public string fEventImgPath { get; set; }
        public string fEventDay { get; set; }
        public string fEventTime { get; set; }
        public string fEventLocation { get; set; }
        public string fEventDescription { get; set; }
        public Nullable<int> fEventFee { get; set; }
        public Nullable<int> fnumCourse { get; set; }
        public string fRemark { get; set; }
    
        public virtual tMemberData tMemberData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEventRegister> tEventRegister { get; set; }
    }
}
