//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace oooooo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tForum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tForum()
        {
            this.tForumComment = new HashSet<tForumComment>();
        }
    
        public int fForumId { get; set; }
        public string fUserId { get; set; }
        public string fPostDate { get; set; }
        public string fWriter { get; set; }
        public string fForumTitle { get; set; }
        public string fForumContent { get; set; }
        public Nullable<int> fForumLike { get; set; }
        public string fForumImage { get; set; }
    
        public virtual tMemberData tMemberData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tForumComment> tForumComment { get; set; }
    }
}
