//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace oooooo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMemberData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMemberData()
        {
            this.tAnnouncement = new HashSet<tAnnouncement>();
            this.tCandidate = new HashSet<tCandidate>();
            this.tCargo = new HashSet<tCargo>();
            this.tEvent = new HashSet<tEvent>();
            this.tEventRegister = new HashSet<tEventRegister>();
            this.tForum = new HashSet<tForum>();
            this.tForumComment = new HashSet<tForumComment>();
            this.tMail = new HashSet<tMail>();
            this.tMail1 = new HashSet<tMail>();
            this.tManagementFee = new HashSet<tManagementFee>();
            this.tNaturalGas = new HashSet<tNaturalGas>();
            this.tReservation = new HashSet<tReservation>();
            this.tUserVote = new HashSet<tUserVote>();
        }
    
        public string fUserId { get; set; }
        public string fBuilding { get; set; }
        public string fPassword { get; set; }
        public string fUserName { get; set; }
        public string fTelePhone { get; set; }
        public string fCellPhone { get; set; }
        public string fHereAddress { get; set; }
        public string fResidenceAddress { get; set; }
        public string fEmail { get; set; }
        public Nullable<System.DateTime> fUpdateDate { get; set; }
        public string fPersonId { get; set; }
        public Nullable<System.DateTime> fBirthday { get; set; }
        public Nullable<int> fnumPeople { get; set; }
        public Nullable<double> fHouseSize { get; set; }
        public Nullable<double> fPublicUsageSize { get; set; }
        public Nullable<int> fnumCarParking { get; set; }
        public Nullable<int> fnumMotorParking { get; set; }
        public Nullable<int> fManagementFee { get; set; }
        public Nullable<int> fParkingClean { get; set; }
        public string fLivingType { get; set; }
        public Nullable<int> fAuthority { get; set; }
        public string fRemark { get; set; }
        public string fProfileImgPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAnnouncement> tAnnouncement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCandidate> tCandidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCargo> tCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEvent> tEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEventRegister> tEventRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tForum> tForum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tForumComment> tForumComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMail> tMail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMail> tMail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tManagementFee> tManagementFee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tNaturalGas> tNaturalGas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReservation> tReservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserVote> tUserVote { get; set; }
    }
}
