//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace oooooo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPay
    {
        public int fPayId { get; set; }
        public string fpayDate { get; set; }
        public string fpayType { get; set; }
        public string fpayVendor { get; set; }
        public string fpayVendorPhone { get; set; }
        public string fProductName { get; set; }
        public string fProductPurpose { get; set; }
        public Nullable<int> fCount { get; set; }
        public Nullable<int> fPrice { get; set; }
        public string fTaxType { get; set; }
        public Nullable<int> fSum { get; set; }
        public string fHandInType { get; set; }
        public string fBuyer { get; set; }
    }
}
